# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_bram_ctrl_0_0/MP1_BRAM_axi_bram_ctrl_0_0.xci
# IP: The module: 'MP1_BRAM_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_bram_ctrl_0_0/MP1_BRAM_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP1_BRAM_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_bram_ctrl_0_0/MP1_BRAM_axi_bram_ctrl_0_0.xci
# IP: The module: 'MP1_BRAM_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_bram_ctrl_0_0/MP1_BRAM_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP1_BRAM_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
