# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/MP1_BRAM_axi_smc_0.xci
# IP: The module: 'MP1_BRAM_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/bd_42d3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_0/bd_42d3_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_1/bd_42d3_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_2/bd_42d3_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_3/bd_42d3_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_4/bd_42d3_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_5/bd_42d3_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_6/bd_42d3_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_7/bd_42d3_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_8/bd_42d3_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_9/bd_42d3_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_10/bd_42d3_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_11/bd_42d3_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_12/bd_42d3_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_1/bd_42d3_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_1/bd_42d3_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_5/bd_42d3_s00a2s_0_ooc.xdc

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_6/bd_42d3_sarn_0_ooc.xdc

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_7/bd_42d3_srn_0_ooc.xdc

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_8/bd_42d3_sawn_0_ooc.xdc

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_9/bd_42d3_swn_0_ooc.xdc

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_10/bd_42d3_sbn_0_ooc.xdc

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_11/bd_42d3_m00s2a_0_ooc.xdc

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP1_BRAM_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/MP1_BRAM_axi_smc_0.xci
# IP: The module: 'MP1_BRAM_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/bd_42d3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_0/bd_42d3_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_1/bd_42d3_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_2/bd_42d3_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_3/bd_42d3_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_4/bd_42d3_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_5/bd_42d3_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_6/bd_42d3_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_7/bd_42d3_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_8/bd_42d3_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_9/bd_42d3_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_10/bd_42d3_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_11/bd_42d3_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_12/bd_42d3_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_1/bd_42d3_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_1/bd_42d3_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_5/bd_42d3_s00a2s_0_ooc.xdc

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_6/bd_42d3_sarn_0_ooc.xdc

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_7/bd_42d3_srn_0_ooc.xdc

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_8/bd_42d3_sawn_0_ooc.xdc

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_9/bd_42d3_swn_0_ooc.xdc

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_10/bd_42d3_sbn_0_ooc.xdc

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/bd_0/ip/ip_11/bd_42d3_m00s2a_0_ooc.xdc

# XDC: d:/Labs/MiniProject_1/MiniProject_1.srcs/sources_1/bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP1_BRAM_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
