# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/MP1_BRAM/MP1_BRAM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP1_BRAM || ORIG_REF_NAME==MP1_BRAM} -quiet] -quiet

# IP: bd/MP1_BRAM/ip/MP1_BRAM_processing_system7_0_0/MP1_BRAM_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP1_BRAM_processing_system7_0_0 || ORIG_REF_NAME==MP1_BRAM_processing_system7_0_0} -quiet] -quiet

# IP: bd/MP1_BRAM/ip/MP1_BRAM_axi_bram_ctrl_0_0/MP1_BRAM_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP1_BRAM_axi_bram_ctrl_0_0 || ORIG_REF_NAME==MP1_BRAM_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/MP1_BRAM/ip/MP1_BRAM_axi_smc_0/MP1_BRAM_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP1_BRAM_axi_smc_0 || ORIG_REF_NAME==MP1_BRAM_axi_smc_0} -quiet] -quiet

# IP: bd/MP1_BRAM/ip/MP1_BRAM_rst_ps7_0_100M_0/MP1_BRAM_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP1_BRAM_rst_ps7_0_100M_0 || ORIG_REF_NAME==MP1_BRAM_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/MP1_BRAM/ip/MP1_BRAM_axi_bram_ctrl_0_bram_0/MP1_BRAM_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP1_BRAM_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==MP1_BRAM_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# XDC: bd/MP1_BRAM/MP1_BRAM_ooc.xdc
